### ISSUE TITLE
Dumping Firmware from Jura WiFi 

### ISSUE THREAD

**Issue by Sebbeben** [Jutta-Proto/protocol-cpp#13]
i remember i saw a kind of guide here some year ago? together with the picture where wires are soldered to the Jura WiFi pcb, is this information somewhere?

**Comment by COM8** [comment]
@Sebbeben you mean this issue  here: https://github.com/Jutta-Proto/protocol-wifi-cpp

**Comment by Sebbeben** [comment]
Yes, thinking If there are some guidelines how to wire this or what to use software etc.

**Comment by COM8** [comment]
Here are a few tutorials:
https://acassis.wordpress.com/2023/03/22/how-to-copy-dump-flash-memory-of-the-esp32/

For this you need the ESP-IDF:
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/get-started/index.html

And Wiring up (Pinout might be a bit different on es Jura ESP32):
https://nexten.ie/blog/2024/01/14/esp32-firmware-dump/

**Comment by Sebbeben** [comment]
Thanks :) I will try to get the firmware bin, if I succeed I will send it to you

**Comment by Sebbeben** [comment]
BlackVS/ESP32-reversing: A curated list of ESP32 related reversing resourcesgithub.comFound this interesting link9 dec. 2024 kl. 07:14 skrev Fabian Sauter ***@***.***>:﻿
Here are a few tutorials:
https://acassis.wordpress.com/2023/03/22/how-to-copy-dump-flash-memory-of-the-esp32/
For this you need the ESP-IDF:
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/get-started/index.html
And Wiring up (Pinout might be a bit different on es Jura ESP32):
https://nexten.ie/blog/2024/01/14/esp32-firmware-dump/

**Comment by Sebbeben** [comment]
Something got wrong when I replied to the mail notice instead of writing here.

This is the interesting link I found.

https://github.com/BlackVS/ESP32-reversing

I soldered wires to the WiFi module some day ago, connected usb to serial and sent command to read out the flash size but did not suceed, couldn't connect to the esp32

Will continue to try, also will finish the pcb in a soon future so everyone can make their own WiFi dongle

**Comment by COM8** [comment]
Cool!
At one point I already dumped the image and started reverse engineering it in Ghidra but I would have to search for it.

**Comment by Sebbeben** [comment]
i had alot of problem to get the backup created but finally it worked :)

[jura-backup-4M.zip](https://github.com/user-attachments/files/18147400/jura-backup-4M.zip)

**Comment by COM8** [comment]
@Sebbeben awesome!

Thanks for sharing the dump here. I personally won't include it in the repo to avoid a DMCA takedown from Jura.
But I'm fine with it being accessible here as comment.

One thing we could do is host it externally and then Link to it in the README.

**Comment by Sebbeben** [comment]
@COM8 good idea!
I put the .bin file at my repo, but as you say it might be a bad idea 🤔 (thou it is just a backup?) 
maybe put this in a closed group that you need invite for? Like your jura code group?

I'm proceeding well with the pcb also, the problem I had was to get the timing correct when booting in programming mode, a friend showed me how to make a circuit for "auto  reset" controlled by the RTS & CTS 
So I will implement this on my version pcb.

**Comment by Sebbeben** [comment]
![image](https://github.com/user-attachments/assets/62f97705-6a65-43de-96b6-4582edbc1e2a)

getting somewhere now :)

**Comment by Sebbeben** [comment]
@COM8 i ordered some blank pcb's
I will give away them for free if anyone wants to try? But the interested people has to pay for shipping.

![image](https://github.com/user-attachments/assets/911aac8e-e304-4b3c-a924-27990f0ac3f3)
