### ISSUE TITLE
Use "new" protocol for a payment solution. 

### ISSUE THREAD

**Issue by karimj** [Jutta-Proto/protocol-cpp#3]
There are a few projects online that use the "old" serial protocol as way to create a payment system. Reading through the documentation and the available commands it seems that this not (yet?) possible with the "new" protocol implementation. Does anyone have more information about this? Basically it would be needed to active or deactivate the machine and be able to get which type of coffee was made. 

Any help or directions where i can find more information would be greatly appreciated

**Comment by COM8** [comment]
No, the old protocol is not supported. I also can't validate it since I only own a coffee maker supporting the new protocol. But I'm open for contributions here!

**Comment by COM8** [comment]
Here you can find more information about the old protocol: http://protocoljura.wiki-site.com/index.php/Protocol_to_coffeemaker

**Comment by karimj** [comment]
Thanks for the quick response! Maybe i was no clear in the question. Its clear that the old protocol is not supported. 

I'd like to find out if its possible to create a payment system with the new protocol. The commands I have seen so far do not seem to make that possible. I.e. is there a possibility to "lock" the machine with the new protocol, so coffee can only be made after a user is authenticated.

**Comment by sergey-gra** [comment]
Please can you explain what is "new" or "old" protocol? Is that connected with old/new coffee machines? 
I want to buy a Jura E6 coffee machine and use protocol which described here. Is it possible? 

Thanks in advance.

Sincerely, 
Sergey

**Comment by COM8** [comment]
New refers to the ability to plug in a [Smart Connect](https://uk.jura.com/en/homeproducts/accessories/SmartConnect-Main-72167) Dongle from JURA.

As far as I'm aware, all currently sold models support this functionality.

The plug for it is located next to the water tank.
![Untitled](https://user-images.githubusercontent.com/11741404/214521919-76976f46-6904-40ae-9d08-f791145f0c69.png)


And it looks something like this:
![image](https://user-images.githubusercontent.com/11741404/214522077-df45924d-45b7-470a-a1e7-2cda2ed279ae.png)

**Comment by sergey-gra** [comment]
> New refers to the ability to plug in a [Smart Connect](https://uk.jura.com/en/homeproducts/accessories/SmartConnect-Main-72167) Dongle from JURA.
> 
> As far as I'm aware, all currently sold models support this functionality.
> 
> The plug for it is located next to the water tank. ![Untitled](https://user-images.githubusercontent.com/11741404/214521919-76976f46-6904-40ae-9d08-f791145f0c69.png)
> 
> And it looks something like this: ![image](https://user-images.githubusercontent.com/11741404/214522077-df45924d-45b7-470a-a1e7-2cda2ed279ae.png)

I get it. Thank you very much @COM8
