### ISSUE TITLE
Jura E6 switch automation

### ISSUE THREAD

**Issue by sergey-gra** [Jutta-Proto/protocol-cpp#7]
Hello. At first thanks for creating such a great project! The features and functionality of protocol are impressive and it's clear a lot of effort has gone into its development. Keep up the good work, and let me know if there's anything I can do to assist with future developments.

I have one question. I want to buy Jura E6 and try to automate it with your protocol. I saw your huge work which has done. But I didn't notice part for controlling switch located at the right side of the machine. Maybe I missed that part. Do you have implementation of that? Or is there any way to do that?

Thank you for your time and consideration. I look forward to hearing from you soon.

Sincerely,
Sergey

**Comment by COM8** [comment]
@sergey-gra I'm glad these docs are useful for you!

No, the water/milk switch is purely mechanical and is not controllable by software, as far as I'm aware.
I'm currently looking into replacing it with a manual valve, but this might require some extra work.

**Comment by COM8** [comment]
For automating I suggest you take a look at the BT protocol, since it offers far more functionality compared to the serial protocol.

https://github.com/Jutta-Proto/protocol-bt-cpp

**Comment by sergey-gra** [comment]
> For automating I suggest you take a look at the BT protocol, since it offers far more functionality compared to the serial protocol.
> 
> https://github.com/Jutta-Proto/protocol-bt-cpp

Thank you @COM8 for your reply. I want to make this automation through RPI 4 with touchscreen display and payment system. Is it convenient way to use BT protocol for this case?

**Comment by sergey-gra** [comment]
> @sergey-gra I'm glad these docs are useful for you!
> 
> No, the water/milk switch is purely mechanical and is not controllable by software, as far as I'm aware. I'm currently looking into replacing it with a manual valve, but this might require some extra work.



> @sergey-gra I'm glad these docs are useful for you!
> 
> No, the water/milk switch is purely mechanical and is not controllable by software, as far as I'm aware. I'm currently looking into replacing it with a manual valve, but this might require some extra work.



> @sergey-gra I'm glad these docs are useful for you!
> 
> No, the water/milk switch is purely mechanical and is not controllable by software, as far as I'm aware. I'm currently looking into replacing it with a manual valve, but this might require some extra work.

I suppose there's a something like relay which switches on/off by turning the switch. When the coffee machine will arive, I'll try to look into that.

**Comment by COM8** [comment]
> Thank you @COM8 for your reply. I want to make this automation through RPI 4 with touchscreen display and payment system. Is it convenient way to use BT protocol for this case?

In this case, yes I suggest using the BT variant since you can lock the screen with it, so no one is able to circumvent your authentication by just clicking a hardware button.
In case you need some suggestions for how to 3D print a display case, that fits onto your JURA E6, take a look here: https://github.com/Jutta-Proto/hardware-pi

> Will be there a problem when the machine is going off? As I suppose after turning it back on, need to do BT connection again, right? 

You always need to reauthenticate/reconnect once the coffee maker turned off since it cuts power to the serial/BT port.
The easiest way (I'm doing it that way) would be either disable automatic turn off via the JURA app, or continuously try to reconnect with the BT dongle once you loose the connection.

**Comment by COM8** [comment]
Just a short heads up. I will be on vacation from tomorrow until March, so replies will be delayed ;)

**Comment by sergey-gra** [comment]
> The easiest way (I'm doing it that way) would be either disable automatic turn off via the JURA app, or continuously try to reconnect with the BT dongle once you loose the connection.

Ohh, I haven't known that is it possible to disable automatic turn off. Because I have Krups coffee machine and after maximum 30 minutes it turned off. Thank you for your suggestions. Will look into that.

**Comment by sergey-gra** [comment]
> Just a short heads up. I will be on vacation from tomorrow until March, so replies will be delayed ;)

Yes of course, take your time! Wishing you a great vacation!
